# Generated by Django 3.0.4 on 2020-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_number', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('ID_number', models.IntegerField()),
                ('native_place', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生管理',
            },
        ),
    ]
